language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - zip
      env: 
        ENV_CXX=g++-5 
        ENV_CC=gcc-5 
        NIGHTLY_UPLOAD=1
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
            - zip
      env: 
        ENV_CXX=clang++-3.8 
        ENV_CC=clang-3.8 
        NIGHTLY_UPLOAD=0
    
before_script:
  - wget https://github.com/sbx320/premake5-travis/blob/master/premake5?raw=true -O ./premake5 &&
    chmod +x ./premake5 &&
    ./premake5 gmake && 
    cd Build

script: make -j 3 CXX=$ENV_CXX CC=$ENV_CC config=release_x64

# Only upload the gcc build
after_success:
  - "[ $NIGHTLY_UPLOAD -eq 1 ] && [ -z $TRAVIS_TAG ] &&
    cd .. &&
    ./premake5 install_data && 
    ./premake5 compose_files && 
    zip -r Artifact.zip InstallFiles/ &&
    curl -i -F \"branch_name=$TRAVIS_BRANCH\" -F \"commit_hash=$TRAVIS_COMMIT\" -F \"commit_title=$(git log -1 --pretty=%B)\" -F build_type=linux64 -F \"secret=$UPLOAD_SECRET\" -F build_upload=@Artifact.zip https://nightlytest.mtasa.com/api/upload"

notifications:
  irc:
    channels:
      - "irc.gtanet.com#mta.dev"
    on_success: change
    on_failure: always

env:
  global:
      secure: fk2kDz4BD3S4cuUihwn7D+rr8X0ZGltahpYJfZzCL5teSJmwIuJOprlsP92x9eacWLzbOdy1cQxj6FfVIeRxiy2hdyx1q+tloA1i7v+rQmErxzPEkSMMJ2dHemUvG5FzfvH5ZzUarFBZwezIxI78eTs5JLBcwoAVMVIJumoqGqI=

